@endpoint = http://localhost:3000/api/v1/cars


###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{ "make" : "Volkswagen",
  "model" : "CC Passat 3",
  "year" : 1922
}



###

@newCar = {{postACar.response.body._id}}

###
GET {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json
x-api-key: blahblah

###
GET  {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json


###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah


###

DELETE  {{endpoint}}/6ab54827779e84d4aa0e3a18 HTTP/3.0
content-type: application/json
x-api-key: blahblah


###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json
x-api-key: blahblah


